### ISSUE TITLE
Undefined function or variable 'uiprogressdlg'.

### ISSUE THREAD

**Issue by Meysam-Amiri** [alexisInSAR/EZ-InSAR#22]
Hi EZ_InSAR team! I am facing this error with Matlab R2016a. Could the reason be the Matlab version? I didn't see the installation mentioning the specified version. I appreciate your help. 
Setting paths for EZ-InSAR: Matlab Interface for Easy InSAR (Version 2.0.0 Beta)...
Added to path: EZ-InSAR Version 2.0.0 Beta
>> EZ_InSAR
Undefined function or variable 'uiprogressdlg'.

Error in GUIMIESAR (line 34)
pg_figopen = uiprogressdlg(figopen,'Title','Loading of EZ-InSAR Application','Message','Opening the
application');

Error in EZ_InSAR (line 62)
        hmain = GUIMIESAR(miesar_para);
 
MathWorks::System::IUserException [Error using matlab.internal.webwindow (line 197)
Unable to start MATLABWindow process

Error in matlab.ui.internal.desktop.uicontainer.UIContainer/buildWindow (line 164)
            this.CEF = matlab.internal.webwindow(this.URL,this.DebugPort);

Error in matlab.ui.internal.controller.FigureController/createView (line 175)
                this.Container.buildWindow();

Error in matlab.ui.internal.componentframework.WebComponentController/add (line 95)
        obj.createView( parentController, parentView, map );

Error in matlab.ui.internal.controller.WebCanvasContainerController/add (line 49)
            add@matlab.ui.internal.componentframework.WebContainerController( this, webComponent, parentController );

Error in matlab.ui.internal.componentframework.WebControllerFactory/create (line 87)
             component.createController( parentController, [] );
]

**Comment by alexisInSAR** [comment]
Hi, 

The uiprogressdlg command was introduced in R2018a. However, EZ-InSAR should be compatible from R2020b and we have mainly tested EZ-InSAR under MATLAB R2021b. 

Kind regards, 

Alexis
