### ISSUE TITLE
Error using createlistSLC (line 110)

### ISSUE THREAD

**Issue by Meysam-Amiri** [alexisInSAR/EZ-InSAR#23]
Hi @alexisInSAR, I am getting this error about not finding the StartTime. I have attached **tmp_list_SLC.csv** and the result of  `M = readtable('tmp_list_SLC.csv')`.

Is it possible to process already downloaded images simply by putting them in slc dir? For example interferogram generation with pair of images using ISCE? I can do it using jupyter notebooks. I wanted to give it a try using EZ-InSAR which seems pretty easy and then test for Time series. 
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   598    0   598    0     0    254      0 --:--:--  0:00:02 --:--:--   254
100   598    0   598    0     0    178      0 --:--:--  0:00:03 --:--:--   178
100   599    0   599    0     0    154      0 --:--:--  0:00:03 --:--:--   154
100  3521    0  3521    0     0    870      0 --:--:--  0:00:04 --:--:--   870
Error using createlistSLC (line 110)
Unrecognized table variable name 'StartTime'.

Error in manageSLC (line 39)
        createlistSLC([],[],[],miesar_para);

Error in GUIMIESAR>@(src,evt,arg1,arg2)manageSLC(src,evt,'checking',figmiesar.UserData) (line 225)
btslccheck.ButtonPushedFcn = @(src,evt,arg1,arg2) manageSLC(src,evt,'checking',figmiesar.UserData);
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 386)
Error while evaluating Button PrivateButtonPushedFcn.

[tmp_list_SLC.csv](https://github.com/alexisInSAR/EZ-InSAR/files/10796732/tmp_list_SLC.csv)
![m](https://user-images.githubusercontent.com/104680747/220438332-85071072-c574-4f32-8c3f-f73eefe77f3b.png)

**Comment by alexisInSAR** [comment]
Hi,

Please try with the last version of "createlistSLC" available on Github (see issue #21) 

Kind regards, 

Alexis
