### ISSUE TITLE
help

### ISSUE THREAD

**Issue by insarbzh** [alexisInSAR/EZ-InSAR#25]
I met a problem when I check the SLCs，and matlab error display is "Unrecognized function or variable 'dil'.".  I found that the table'm' is null, I guess the reason is that I didn't get the file 'tmp_list_SLC.csv'.
<img width="669" alt="36e0b2a5bea5bea59eacee8e1cc875c" src="https://user-images.githubusercontent.com/127461302/225643212-60f02eb6-93f4-48e0-9c76-4f26016c4593.png">
<img width="832" alt="c31e6e96d840b3649b66c4016d0728f" src="https://user-images.githubusercontent.com/127461302/225643262-3e66cb81-c0c7-43fa-8fe8-8f7567fec887.png">

**Comment by alexisInSAR** [comment]
I don't know exactly what happens. Are you sure about the parameters of SLCs. If you wish, you can share your kml and your SLC parameters.

**Comment by insarbzh** [comment]
This may be caused by the parameters of SLCs, I forgot to confirm before, and the problem has been solved, thank you！
