### ISSUE TITLE
help：Selecting the best reference date problem

### ISSUE THREAD

**Issue by Rick0219** [alexisInSAR/EZ-InSAR#35]
Hi,Alexis
I have met some problems when I use the button "Select the best reference date problem".I choose POD and potinel reference date.

![image](https://user-images.githubusercontent.com/93982725/234905685-a7a5e110-0d37-4f1a-9af1-72ef8d80ce61.png)

**Comment by alexisInSAR** [comment]
Hi, 

Does it work if you use the default settings?

Kind regards, 

Alexis
