### ISSUE TITLE
import cv2 problem

### ISSUE THREAD

**Issue by Matin-GorganSaraj** [alexisInSAR/EZ-InSAR#39]
hello 
when i run the pre-run of isce processing step i face with this problem ( not model named cv2 [i think it's opencv])
![Screenshot (183)](https://user-images.githubusercontent.com/130948662/235311141-65e76de3-88e1-4523-a06f-321fa5e84172.png)
when i check the code i see cv2 don't used in Stack.py then i delete the import cv2 line in Stack.py (line 1646) then this step run well ! 
![Screenshot (184)](https://user-images.githubusercontent.com/130948662/235311260-679a1126-7623-403f-ba4b-1faa5585e454.png)
![Screenshot (185)](https://user-images.githubusercontent.com/130948662/235311269-b15e72fa-40cd-4eae-aee0-fbcf777c2e62.png)
and my question is , the changing into Stack.py can cause me any problem ? 
With all regard
Matin

**Comment by alexisInSAR** [comment]
I think the best solution is just to install cv2: 
````
conda install opencv
````
or 
````
pip3 install opencv-python
````

**Comment by Matin-GorganSaraj** [comment]
yes i install opencv and it runs well , thank you for responding
but i have another quastion ; can i proccess with my gpu in isce2 , i think , i saw something on isce docu but i dont know how to do it.
