### ISSUE TITLE
Name is nonexistents or not a directory: /StaMPS/TRAIN/matlab

### ISSUE THREAD

**Issue by AllendePrieto** [alexisInSAR/EZ-InSAR#55]
Hi Alex!
In the file "config_InSARenv.rc", the variable TOOL_DIR is defined, but... the variable that defines the path of the TRAIN folder is tool_DIR. This implies that the search from Matlab doesn't work, resulting in the following error

![imagen](https://github.com/alexisInSAR/EZ-InSAR/assets/131383377/3616709d-60b2-4af2-802e-8bf2f19a74c4)

I solved it by adding a new line: export Tool_DIR=$TOOL_DIR 

King Regards!!

Cristina

**Comment by alexisInSAR** [comment]
Thank you Cristina, 

I will add the new alias in the file. 

Kind regards, 

Alexis
