### ISSUE TITLE
Changes in https://scihub.copernicus.eu/

### ISSUE THREAD

**Issue by FranckzGithub** [alexisInSAR/EZ-InSAR#71]
A few days ago i was using this tool succesfully but sentinel data was moved i mean : https://scihub.copernicus/, i think is moved to https://dataspace.copernicus.eu/, so the automatic downloading of Orbits in fetchOrbit.py file is not working, i suggest review this issue... Many Thanks in advance

**Comment by alexisInSAR** [comment]
Hi, 

The new version (2.2.0) allows you to download orbit files from the ASF server. Try it if you wish. 

Kind regards, 

Alexis

**Comment by FranckzGithub** [comment]
i will try, thank you very much!!!

**Comment by A220N1** [comment]
Hi Alexis,

Perhaps it's intentional, but in version 2.2.0 the pathinformation.txt contains your ID and your password.

**Comment by alexisInSAR** [comment]
Thank you.

**Comment by FranckzGithub** [comment]
![Screenshot from 2023-11-26 22-49-51](https://github.com/alexisInSAR/EZ-InSAR/assets/115663434/8e524852-2336-42f0-9f16-4d57e7c47e92)
Your modifications are amazing, i think this code is amazing and help to process InSAR data, i faced this problem, when i downloaded the orbits from 20200305, it was saved in a folder with the name "20200307", and the code cannot recognize the date, so i changed all names of folders (in this specific case 20200307 to 20200305) of orbit folders.... and it worked, i dont know if this is an issue or not, but it worked for me, i would suggest review this issue, and thank you for you support =D
