### ISSUE TITLE
ERROR IN STAMPS PS STEP 5

### ISSUE THREAD

**Issue by marvelraj25** [alexisInSAR/EZ-InSAR#87]
Hello Sir , there is an issue in step 5 in PS processing showing as

![stamps](https://github.com/alexisInSAR/EZ-InSAR/assets/163887213/027c9554-d899-4825-9254-fc2467442183)

Please provide the possible solution

**Comment by alexisInSAR** [comment]
Hi, 

Can you give me more information? 

Kind regards, 

Alexis

**Comment by marvelraj25** [comment]
The error was  resolved on changing the select method to PERCENT instead of DENSITY in step 3
